### ISSUE TITLE
Can i have this web app link please thank you 😊 🙏 

### ISSUE THREAD

**Issue by Aruraka** [mr-anonymous-official/TheFireflix#3]

**Comment by karthikraja001** [comment]
https://karthikraja001.github.io/TheFireflix/#/

Thanks for remainding me of my college project.

**Comment by Aruraka** [comment]
Hii there I can't find search button for finding series in this app ..can u
please help?

**Comment by Aruraka** [comment]
Hi ,whenever I try to open the searched series ..it's just rotating..nothing is appearing..pls fix this

**Comment by karthikraja001** [comment]
Sorry to say this, Currently i just have the build version code of this web app. I lost the source code of this project.

**Comment by Aruraka** [comment]
Ooh that's sad to know🫠🙃

**Comment by karthikraja001** [comment]
Sorry for the disappointment🫠

**Comment by Aruraka** [comment]
It's okay tho..btw can u recommend me some other app which can download all tv shows in different quality please

**Comment by karthikraja001** [comment]
I think you can use popcorn bot from telegram for downloading tv shows and use yts.mx for downloading english movies. Mostly you can get all the series and shows in thepiratebay as torrent.

**Comment by Aruraka** [comment]
Thanks but I wanna download asian series such as korean nd chinese ..can u pls recommend me such apps which can download these?

**Comment by karthikraja001** [comment]
I'm not sure where can we donload those series💀

**Comment by Aruraka** [comment]
Oh okay
